### ISSUE TITLE
ini kenapa ya bang selalu 403?

### ISSUE THREAD

**Issue by mobplay-script** [bactiar291/dawn-validator#1]
![image](https://github.com/user-attachments/assets/e114ec66-8616-4f1c-acc4-3024eaebd707)

**Comment by bactiar291** [comment]
Ambil ulang bearernya bg

Pada Rab, 30 Okt 2024 21.45, Abdi Prasetya ***@***.***>
menulis:

**Comment by mobplay-script** [comment]
oh bukan bang, itu bearer fresh, ternyata tambahin sedikit proxy jalan

**Comment by bactiar291** [comment]
Oke bg

Pada Rab, 30 Okt 2024 21.57, Abdi Prasetya ***@***.***>
menulis:
